New profile view
DV1512/frontend pull request #21
Opened 2024-10-22 19:02 UTC by muaathaw

profile view is now done, any suggestion before i merge?

2024-10-22 19:40 UTC, EmEhPa commented
Please merge main into your branch first.

2024-10-23 08:01 UTC, EmEhPa requested changes

2024-10-23 08:02 UTC, EmEhPa commented
See on Figma, maybe include so we the name will be visible

2024-10-23 08:04 UTC, retrokiller543 requested changes

2024-10-23 08:04 UTC, retrokiller543 commented on src/views/ProfileView.vue
> +// Method to handle profile updates
this comment is not needed, the name of the function describes the purpose

2024-10-23 08:04 UTC, retrokiller543 commented on src/views/ProfileView.vue
> +  // Add code to make an API call to update the user's profile
remove GPT comment

2024-10-23 08:04 UTC, retrokiller543 commented on src/views/ProfileView.vue
> +// Method to handle account deletion
same as before, its not needed

2024-10-23 08:04 UTC, retrokiller543 commented on src/views/ProfileView.vue
> +  // Handle profile update logic (send updated data to the server)
remove the console.log and comment and replace with a `TODO: <what to do in the future>`

2024-10-23 08:04 UTC, retrokiller543 commented on src/views/ProfileView.vue
> +    // Add code to make an API call to delete the user's account
again replace with `TODO` comment

2024-10-23 08:04 UTC, retrokiller543 commented on src/views/ProfileView.vue
> +// Method to handle declining (canceling) changes
not needed

2024-10-23 08:04 UTC, retrokiller543 commented on src/views/ProfileView.vue
> +    // Reset the form fields to their previous values or leave empty if no previous values
not needed aswell, code explains itself

2024-10-23 08:04 UTC, retrokiller543 commented on src/views/ProfileView.vue
> +        <!-- Profile form content -->
remove

2024-10-23 08:04 UTC, retrokiller543 commented on src/views/ProfileView.vue
> +          <!-- Name Field -->
remove

2024-10-23 08:04 UTC, retrokiller543 commented on src/views/ProfileView.vue
> +          <!-- Username Field -->
remove

2024-10-23 08:04 UTC, retrokiller543 commented on src/views/ProfileView.vue
> +          <!-- Email Field -->
remove

2024-10-23 08:04 UTC, retrokiller543 commented on src/views/ProfileView.vue
> +          <!-- Password Fields (optional) -->
remove

2024-10-23 08:04 UTC, retrokiller543 commented on src/views/ProfileView.vue
> +          <!-- Submit Button -->
remove

2024-10-23 08:04 UTC, retrokiller543 commented on src/views/ProfileView.vue
> +        <!-- Additional Actions: Decline and Delete Account -->
remove

2024-10-23 08:12 UTC, retrokiller543 commented on src/views/ProfileView.vue
> +// Method to handle profile updates
Not needed, function name describes iteself

2024-10-23 08:13 UTC, muaathaw commented on src/views/ProfileView.vue
> +const handleDeclineChangesClick = () => {
NO! it´s just a function to restore the changes, in case the user changes something wrong or regrets it

2024-10-23 08:47 UTC, retrokiller543 approved these changes
Looks good, there is a comment that might have been missed but im happy with the changes made

2024-10-23 12:18 UTC, EmEhPa approved these changes
Ok! The main design is there so we can merge. We will during next team team implement the logic of this view

2024-10-23 13:24 UTC, merged