Feature/login
DV1512/frontend pull request #23
Opened 2024-11-04 12:32 UTC by EmEhPa

The feature for login is done

2024-11-04 13:49 UTC, retrokiller543 requested changes
Please remove old test code

2024-11-04 13:49 UTC, retrokiller543 commented on src/main.ts
> +passwordLogin('emma.ehnpaulsson@gmail.com', 'test').then((res) => {
Please remove

2024-11-04 14:42 UTC, retrokiller543 approved these changes

2024-11-05 07:32 UTC, muaathaw approved these changes
looks fine from my side !

2024-11-05 07:51 UTC, merged