Feature/login password
DV1512/frontend pull request #25
Opened 2024-11-06 14:46 UTC by EmEhPa

It appears that the chatview branch is also included in this PR, though it’s not fully complete yet.

For the signup and login functionalities:

- Users can sign up with some requirements on the password, etc. After a successful signup, they’re registered as users in the database and redirected to the login page.
- If the user enters an incorrect password during signup, they won’t be registered in the database, so they will not have an active session.
- If all credentials are correct, the user is successfully logged in and registered in the database.

2024-11-06 15:03 UTC, muaathaw approved these changes
a lot of changes at once, a bit hard to keep up with everything but still looks ok!

2024-11-07 13:22 UTC, retrokiller543 requested changes

2024-11-07 13:22 UTC, retrokiller543 commented on src/views/LogInView.vue
> +      <div class="columns is-centered mt-5">
Moving this to its own component would be good so we can reuse the same logic for login/signup with an oauth provider all in one place instead of in 2 different places

2024-11-07 13:22 UTC, retrokiller543 commented on src/views/SignUpView.vue
> +      <div class="columns is-centered mt-5">
same comment about splitting into its own component

2024-11-07 13:22 UTC, retrokiller543 commented on src/views/services/authService.ts
> +    fetch('http://localhost:9999/api/v1/oauth/register', {
look and see how we could add this as an env variable so we dont have hardcoded url to our backend or any other potential service, the sdk needs this change aswell but for now its a lesser issue as its just one location in the sdk where we need to adjust, where as the frontend will potentially have more than one

2024-11-07 14:52 UTC, EmEhPa commented on src/views/SignUpView.vue
> +      <div class="columns is-centered mt-5">
same as above, should be done

2024-11-08 08:31 UTC, EmEhPa commented on src/views/ChatView.vue
> +        <div class="chat-area">
I would say this is implemented

2024-11-10 20:45 UTC, EmEhPa commented on src/views/ChatView.vue
> +const messages = ref([{ text: 'Hello! How can I assist you today?', sender: 'bot' }])
I think this is resolved

2024-11-15 09:15 UTC, EmEhPa commented on src/views/ChatView.vue
> +  border-right: 1px solid #7c7777;
We fix in dark/light mode PR

2024-11-15 09:28 UTC, EmEhPa commented on src/views/services/authService.ts
> +    fetch('http://localhost:9999/api/v1/oauth/register', {
Fixed

2024-11-15 09:29 UTC, EmEhPa commented on src/views/ChatView.vue
> +<script setup lang="ts">
will fix in upcoming bransches

2024-11-15 09:29 UTC, merged