Feature/auth
DV1512/frontend pull request #8
Opened 2024-10-02 07:44 UTC by EmEhPa

knapp

2024-10-02 07:50 UTC, retrokiller543 commented on src/components/Button.vue
> +      // Emit a 'click' event with an optional payload
Not needed as there already is a click event built in to html, this would be useful if we have a non standard place where we want to trigger a specific event, the event could then be called something like `button_clicked` or `button-clicked`

2024-10-02 07:51 UTC, retrokiller543 commented on src/components/Button.vue
> +      type: [Object, String, Number, Boolean, Array],
not needed unless the component has logic to add to a event itself, for example a file upload button could send a payload of the file that has been uploaded up to its parent, but that still would mean that the `payload` prop would never be used

2024-10-02 07:53 UTC, retrokiller543 commented on src/views/HomeView.vue
> +      window.location.href = 'http://localhost:9999/oauth/google/login';
This path will in the future be updated to `http://localhost:9999/api/v1/oauth/google/login` to follow api versioning standards

2024-10-02 07:53 UTC, retrokiller543 commented on src/views/HomeView.vue
> +      window.location.href = 'http://localhost:9999/oauth/github/login';
see comment above

2024-10-02 07:54 UTC, retrokiller543 commented on src/components/Button.vue
> +  padding: 10px 20px;
try to if possible to use responsive types like `rem` for anything that is not `border-radius`

2024-10-02 07:55 UTC, retrokiller543 commented on src/components/Button.vue
> +  font-size: 16px;
Same as prev comment about responsive types

2024-10-02 07:55 UTC, retrokiller543 commented on src/views/HomeView.vue
> +  margin-top: 10px;
Same as prev comment about responsive types

2024-10-02 07:55 UTC, retrokiller543 commented on src/views/HomeView.vue
> +  padding: 10px 20px;
Same as prev comment about responsive types

2024-10-02 07:55 UTC, retrokiller543 commented on src/views/HomeView.vue
> +  margin-top: 10px;
Same as prev comment about responsive types

2024-10-02 07:55 UTC, retrokiller543 commented on src/views/HomeView.vue
> +  padding: 10px 20px;
Same as prev comment about responsive types

2024-10-02 08:00 UTC, muaathaw reviewed
Looks good !

2024-10-02 08:07 UTC, muaathaw approved these changes

2024-10-02 09:30 UTC, retrokiller543 requested changes

2024-10-02 09:30 UTC, retrokiller543 commented on src/components/Button.vue
> +    @click="$emit('click')"
again we do not need to emit anything

2024-10-05 09:44 UTC, retrokiller543 approved these changes

2024-10-05 09:44 UTC, merged